title = 'CakeMC 帮助文档'
description = 'CakeMC 官方帮助文档'
evergreen = true
[locales]
'/' = { lang = 'zh-CN', title = 'CakeMC 帮助文档' }

[themeConfig]
repo = 'cake-mc/docs'
docsBranch = 'master'
editLinks = false

[themeConfig.locales.'/']
editLinkText = '帮助我们完善这个页面'
lastUpdated = '最后更新'

[[themeConfig.locales.'/'.nav]]
text = '主页'
link = '/'
[[themeConfig.locales.'/'.nav]]
text = 'RTMWorld'
link = '/rtmworld/'
[[themeConfig.locales.'/'.nav]]
text = 'Cake Launcher'
link = '/cake-launcher/'
[[themeConfig.locales.'/'.nav]]
text = 'CakeSkin'
link = '/cakeskin/'
[[themeConfig.locales.'/'.nav]]
text = 'TZMTR'
link = '/tzmtr/'

[themeConfig.locales.'/'.sidebar]
'/rtmworld/' = [
  '/rtmworld/server-type',
  '/rtmworld/how-to-play',
]
'/cake-launcher/' = []

'/cakeskin/' = [
  '/cakeskin/about',
  '/cakeskin/how-to-use',
  '/cakeskin/privacy',
  '/cakeskin/tos',
]

'/tzmtr/' = []